name:                mmm
version:             0.1.0.0
github:              "githubuser/mmm"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

language: GHC2021

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- LambdaCase
- LinearTypes
- OverloadedStrings
- OverloadedLists
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- ViewPatterns

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mmm#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- deepseq
- flatparse
- hashable
- linear
- parser-combinators
- template-haskell
- text
- th-serde
- unordered-containers
- uuid-types
- varcomp
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  mmm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mmm
    - hspec
    - binary
