name:                mmm
version:             0.1.0.0
github:              "axionbuster/mmm"
license:             BSD-3-Clause
author:              "axionbuster"
maintainer:          "axionbuster@gmail.com"
copyright:           "2025 axionbuster"

language: GHC2021

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- LambdaCase
- LinearTypes
- MultiWayIf
- OverloadedStrings
- OverloadedLists
- OverloadedRecordDot
- PatternSynonyms
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeFamilies
- UndecidableInstances
- ViewPatterns

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Minecraft 1.21.4 implementation in Haskell
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/axionbuster/mmm#readme>

dependencies:
- adjunctions
- async
- base >= 4.7 && < 5
- bytestring
- containers
- deepseq
- effectful
- effectful-th
- flatparse
- hashable
- io-streams
- lens
- linear
- network
- network-run
- parser-combinators
- random
- stm
- template-haskell
- text
- th-serde
- unliftio
- unordered-containers
- uuid-types
- vector
- zlib

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources:
  - src/M/Crypto/crypto.c
  extra-libraries:
  - crypto
  cc-options:
  - -Wall
  - -Wextra
  - -Werror
  - -Wno-unused-parameter
  - -O2

tests:
  mmm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - mmm
    - hspec
    - binary
