{-# OPTIONS_GHC -Wno-missing-export-lists #-}

-- | Packet definitions for the V769 (Java 1.21.4) protocol.
--
-- WARNING: Much of this module was generated by AI under human guidance.
-- It is not guaranteed to be correct.
module M.V769
  ( module M.V769.C,
    module M.V769.H,
    module M.V769.L,
    module M.V769.P,
    module M.V769.S,
  )
where

import M.V769.C
import M.V769.H
import M.V769.L
import M.V769.P
import M.V769.S
